// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtpaxovmulvjmlqlqytd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10cGF4b3ZtdWx2am1scWxxeXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTQyMjcsImV4cCI6MjA3MDg5MDIyN30.6eTazwsVsA4JGv0ZVZnP0XGlnj4ZRQOPztzobWtgOVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});